general:
  problem: zdt1
  n_var: 6
  n_obj: 2
  n_init_sample: 20
  ref_point:
  - 1.0
  - 6.0
  batch_size: 5
  seed: 0
  algo: tsemo
  n_process: 1
surrogate:
  surrogate: ts
  n_spectral_pts: 100
  nu: 5
  mean_sample: false
acquisition:
  acquisition: identity
solver:
  solver: nsga2
  pop_size: 100
  n_gen: 200
  pop_init_method: nds
selection:
  selection: hvi
