general: 
  n_init_sample: 20
  batch_size: 5
  n_process: 1
problem: 
  name: zdt1
  n_var: 6
  n_obj: 2
  ref_point:
  - 1.0
  - 6.0
algorithm: 
  name: tsemo
  surrogate:
    name: ts
    n_spectral_pts: 100
    nu: 5
    mean_sample: false
  acquisition:
    name: identity
  solver:
    name: nsga2
    pop_size: 100
    n_gen: 200
    pop_init_method: nds
  selection:
    name: hvi
