general: 
  n_init_sample: 20 # number of initial random samples
  batch_size: 5
  n_iter: 10 # number of algorithm iterations
  n_process: 1 # number of parallel processes used in algorithm
problem: 
  name: zdt1
  n_var: 6
  n_obj: 2
  var_name: # name of design variables (optional)
  - x1
  - x2
  - x3
  - x4
  - x5
  - x6
  obj_name: # name of performance objectives (optional)
  - f1
  - f2
  ref_point: # reference point for hypervolume calculation (optional)
  - 1.0
  - 6.0
algorithm: 
  name: tsemo
  surrogate:
    name: ts
    n_spectral_pts: 100
    nu: 5
    mean_sample: false
  acquisition:
    name: identity
  solver:
    name: nsga2
    pop_size: 100
    n_gen: 200
    pop_init_method: nds
  selection:
    name: hvi
